#!/bin/bash

echo "###################################################################################################"
echo "#                                    Lattice optimization script                                  #"
echo "#                                   *****************************                                 #"
echo "#                                                                                                 #"
echo "#                       Created by: George Yumnam (UG, Materials Science)                         #"
echo "#                                   Materials Research Centre                                     #"
echo "#                                   Indian Institute of Science, Bangalore                        #"
echo "###################################################################################################"

PREFIX="Cu"

ELEMENT="Cu"

MPIRUN="mpirun.openmpi"

ESPRESSO_PW="pw.x"

# This script is meant for optimizing the lattice parameters of the crystal structure of Cu as designed.
mkdir 2-LATT_OPT-new
cp Cu.pbe.UPF 2-LATT_OPT-new
cd 2-LATT_OPT-new

LATT="9.6 9.8 10.0 10.2 10.4 10.6 10.8"

for lat in $LATT
do
	echo " "
	echo "Calculating the energy for crystal structure with Lattice parameter = "$lat 
	mkdir latt.$lat
	cp Cu.pbe.UPF latt.$lat
	cd latt.$lat
	echo " "
	echo "Entering the directory: latt."$lat
	echo " "
	echo "Now writing the input file!!!"
	echo " "
	cat > Cu.scf.latt_$lat.in<< EOF
 &CONTROL
                 calculation = 'scf' ,
                restart_mode = 'from_scratch' ,
                      outdir = './' ,
                  pseudo_dir = './' ,
                      prefix = '$PREFIX' ,
                   verbosity = 'low' ,
 /
 &SYSTEM
                       ibrav = 2,
                   celldm(1) = $lat,
                         nat = 2,
                        ntyp = 1,
                     ecutwfc = 60 ,
		 occupations = 'smearing' ,
                    smearing = 'gaussian' ,
                     degauss = 0.003
 /
 &ELECTRONS
                    conv_thr = 1d-07 ,
                 mixing_mode = 'plain' ,
                 mixing_beta = 0.7 ,
             diagonalization = 'david' ,
 /
ATOMIC_SPECIES
   Cu   63.54600  Cu.pbe.UPF
ATOMIC_POSITIONS alat
   Cu      0.000000000    0.000000000    0.000000000
   Cu      0.250000000    0.250000000    0.250000000
K_POINTS automatic
  9 9 9   0 0 0
EOF
	echo "Now calculating the energy of this crystal structure!"
	echo "Generating -->> Cu.scf.latt_"$lat".out"
	$MPIRUN -np 4 $ESPRESSO_PW < Cu.scf.latt_$lat.in > Cu.scf.latt_$lat.out
	echo " "
	echo "Generated files and directories in this case: "
	echo " "
	ls
	cd ../

	tot_en=`grep "!    total energy" ./latt.$lat/Cu.scf.latt_$lat.out | awk '{printf "%15.12f\n",$5}'`
	echo "Finally, The total energy for the given lattice parameter is:"
	echo " "
	echo $lat "<------> " $tot_en
	echo "$lat $tot_en" >> $ELEMENT.latt_opt.dat
	echo " "
	echo " "
	echo "***************************************************"
	echo "***************************************************"
	echo "********* DONE - iteration - " $lat " ****************"
	echo "***************************************************"
	echo "***************************************************"
done

# The following code is meant for plotting the lattice optimation using Xmgrace
# If you don't have Xmgrace installed in your system, the first install it
# Otherwise, Please comment out the following lines
echo " "
echo " "
echo "******************************************************************************"
echo "******************************************************************************"
echo "********* DONE - CALCULATION - INITIATING XMGRACE FOR PLOTTING ***************"
echo "******************************************************************************"
echo "******************************************************************************"
echo " "
echo " "
echo "Plotting diagram now!!!"

xmgrace -free -nxy $ELEMENT.latt_opt.dat

echo " "
echo " "
echo "############################################################################## "
echo "############################################################################## "
echo "##                   Finally the computation is done now!!!                 ## " 
echo "##                                 BYE BYE!!!                               ## "
echo "############################################################################## "
echo "############################################################################## "
echo " "
echo " "
